### ISSUE TITLE
Consider using `int` for port argument/DefaultPort

### ISSUE THREAD

**Issue by jsocol** [PagerDuty/godspeed#16]
This is definitely a nit, but it's also a little surprising when you run into it.

Trying to use godspeed with the `flag` module is a bit confusing/annoying, since you have to cast the value to a `uint16`. It's even worse if you want to use the `godspeed.DefaultPort` as a default for the flag:

```go
var sHost = flag.String("dd-host", godspeed.DefaultHost, "datadog agent host")
var sPort = flag.Int("dd-port", int(godspeed.DefaultPort), "datadog agent port")

func main() {
    flag.Parse()
    statsd, err := godspeed.New(*sHost, uint16(*sPort), false)
    statsd.Incr("foo")
}
```

Like I said, a nit, and not a big deal, but it caught me by surprise, especially since that pattern worked so well for `godspeed.DefaultHost`.

**Comment by theckman** [comment]
:+1: valid concern, will get something out for it soon.

**Comment by theckman** [comment]
I think it's better to have this return an error, instead of having to worry about your type. `uint16` just happens to encompass the range of all TCP/UDP ports, which is why I had used it originally.

**Comment by jsocol** [comment]
Awesome! And thanks so much for the library, it was a breeze to drop in and use.
